services:
  db:
    image: postgres:16-alpine
    container_name: agro-notes-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-agro}
      TZ: ${TZ:-America/Argentina/Cordoba}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ./agro-notes-api
      dockerfile: Dockerfile
    container_name: agro-notes-api
    environment:
      # App
      NODE_ENV: ${NODE_ENV:-development}
      TZ: ${TZ:-America/Argentina/Cordoba}
      PORT: ${API_PORT:-4000}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
      # DB (dentro de la red docker)
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-postgres}
      DB_NAME: ${DB_NAME:-agro}
      TYPEORM_SYNC: ${TYPEORM_SYNC:-true}
      TYPEORM_LOGGING: ${TYPEORM_LOGGING:-false}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT:-4000}:4000"
    restart: unless-stopped

  web:
    build:
      context: ./agro-notes
      dockerfile: Dockerfile
    container_name: agro-notes-web
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      TZ: ${TZ:-America/Argentina/Cordoba}
      # MUY IMPORTANTE: el front corre en el navegador del usuario.
      # Para llamadas desde el browser, apuntamos a localhost:4000 (mapeado por el servicio 'api').
      NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE:-http://localhost:4000}
    depends_on:
      - api
    ports:
      - "${WEB_PORT:-3000}:3000"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: agro-notes-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      # Si querés usar un dominio raro tipo .local, descomentá:
      # PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: 'agro-notes.local'
      # PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  db_data:
  pgadmin_data:
