services:
  api:
    build:
      context: ./agro-notes-api
      dockerfile: Dockerfile
    container_name: agro-notes-api
    environment:
      NODE_ENV: production
      TZ: ${TZ:-America/Argentina/Cordoba}
      PORT: ${API_PORT:-4000}
      CORS_ORIGIN: ${CORS_ORIGIN:-https://agro-notes.vercel.app}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-postgres}
      DB_NAME: ${DB_NAME:-agro}
      TYPEORM_SYNC: ${TYPEORM_SYNC:-false}
      TYPEORM_LOGGING: ${TYPEORM_LOGGING:-false}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT:-4000}:4000"
    restart: unless-stopped

  web:
    build:
      context: ./agro-notes
      dockerfile: ./Dockerfile
    container_name: agro-notes-web
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      TZ: ${TZ:-America/Argentina/Cordoba}
      NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE:-http://api:4000}
    depends_on:
      - api
    ports:
      - "${WEB_PORT:-3000}:3000"
    restart: unless-stopped
